### PR TITLE
Call it '*NIX' and not 'NIX'

### PR DESCRIPTION
**Pull request by Mstrodl**
Call it '*NIX' and not 'NIX'

### CODE REVIEW

**Comment by andersevenrud** [comment]
Could you please change your commit message to something like "Updated installation section text" or something like that ?

**Comment by Mstrodl** [comment]
Okay.

**Comment by andersevenrud** [comment]
I fixed the commit message

**Comment by Mstrodl** [comment]
Sorry I thought you meant the PR name.

**Pull request closed without merging**
