### PR TITLE
Update demo URL to v3

### PR DESCRIPTION
**Pull request by filips123**
Update demo URL to v3.

### CODE REVIEW

**Comment by andersevenrud** [comment]
The reason I haven't swapped this out myself yet is because I need to retire my server and set up a new one. It became really unstable after it was migrated over to another HV. On top of that, it's running an ancient Ubuntu, so there seems to be some intermittent issues with docker for unknown reasons.

I'll get that fixed ASAP and run this PR.

**Comment by filips123** [comment]
@andersevenrud If you will change your server, it would be better to change v3 demo URL to `https://demo.os-js.org/` and v2 to `https://demo.os-js.org/v2`. You then won't need this PR.

**Comment by andersevenrud** [comment]
That was the plan :)

**Comment by filips123** [comment]
@andersevenrud Currently, [v3 demo](https://demo.os-js.org/v3/) doesn't work because it just shows "503 Service Unavailable". Can you check this?

**Comment by andersevenrud** [comment]
You were actually faster notifying me about this than the monitoring system :laughing: 

The server was rebooted 8 minutes before you posted your message and it seems like Docker never went back up again. It should be coming back on-line within a few minutes.

Thanks!

Also, you just reminded me that I need to switch over to the new server. I'll look at where I dropped off and change the DNS :blush:

**Comment by andersevenrud** [comment]
Okay. The new server now runs v2 and v3 just fine. I just gotta migrate my SSL certificates, then update the DNS records. However, it's getting a bit late here, so I'll do this tomorrow.

We can then *finally* merge this and update the website.

**Comment by andersevenrud** [comment]
I decided to migrate `www.` and `manual.` servers first and keep an eye open for the same issues I've had with the [now] old setup. Seems like it's all OK, so I've updated the DNS records for `demo.` as well and it should take effect within an hour or so.

However, before going live with this PR I really want to convert the games in the v2 demo, because it seems those are among the most popular ones (at least judging from analytics bounce times), so I'm on that as we speak :blush:

**Comment by andersevenrud** [comment]
Also stumbled across this bug: https://github.com/os-js/osjs-pdfreader-application/issues/3

**Comment by andersevenrud** [comment]
I actually moved `demo.os-js.org -> demo-legacy.os-js.org` and `demo.os-js.org/v3 -> demo.os-js.org` , so I'm closing this one....430 days later :joy:

**Pull request closed without merging**
